# Generated by Django 5.2.15 on 2026-06-06 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lecturer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_no', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=64)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='office_staff', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_no', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Office staff',
                'verbose_name_plural': 'Office staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matric_no', models.CharField(max_length=64, unique=True)),
                ('programme', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Deferred', 'Deferred'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=16)),
                ('intake_semester', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coordinator', serialize=False, to='accounts.lecturer')),
                ('programme_managed', models.CharField(blank=True, default='', max_length=255)),
                ('appointed_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='panel', serialize=False, to='accounts.lecturer')),
                ('max_appointments', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Panel member',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supervisor', serialize=False, to='accounts.lecturer')),
                ('max_supervisees', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
