# Generated by Django 5.2.15 on 2026-06-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lecturer_officestaff_student_remove_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistry',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registry', serialize=False, to='accounts.student')),
                ('ic_number', models.CharField(blank=True, default='', max_length=32)),
                ('passport_number', models.CharField(blank=True, default='', max_length=32)),
                ('nationality', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.TextField(blank=True, default='')),
                ('programme_mode', models.CharField(blank=True, choices=[('Coursework', 'Coursework'), ('Research', 'Research'), ('Mixed Mode', 'Mixed Mode')], default='', max_length=32)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('mode_of_study', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='', max_length=32)),
                ('current_semester', models.CharField(blank=True, default='', max_length=64)),
                ('max_semester', models.CharField(blank=True, default='', max_length=64)),
                ('expected_completion', models.CharField(blank=True, default='', max_length=64)),
                ('sponsor', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student registry detail',
                'verbose_name_plural': 'Student registry details',
            },
        ),
    ]
