# Generated by Django 5.2.15 on 2026-08-17 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studentregistry"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="lifecycle_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="lifecycle_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lecturer_lifecycle_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="lifecycle_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("RETIRING", "Retiring"),
                    ("RETIRED", "Retired"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ParticipantLifecycleAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(max_length=32)),
                ("new_status", models.CharField(max_length=32)),
                ("reason", models.TextField()),
                ("affected_records", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participant_lifecycle_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_audits",
                        to="accounts.lecturer",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_audits",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lecturer__isnull", True), ("student__isnull", False)
                            ),
                            models.Q(
                                ("lecturer__isnull", False), ("student__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="participant_audit_exactly_one_subject",
                    )
                ],
            },
        ),
    ]
