# Generated by Django 5.2.15 on 2026-08-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_notifications', models.BooleanField(default=True)),
                ('announcement_alerts', models.BooleanField(default=True)),
                ('deadline_reminders', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
