# Generated by Django 5.2.17 on 2026-09-20 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_lecturer_lifecycle_changed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinatorDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme", models.CharField(max_length=255)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("justification", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinator_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_coordinator_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_coordinator_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                        name="delegation_valid_dates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revocation_reason", ""),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                            ),
                            models.Q(
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                                models.Q(("revocation_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="delegation_revocation_complete",
                    ),
                ],
            },
        ),
    ]
