# Generated by Django 5.2.17 on 2026-09-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lecturer_lifecycle_changed_at_and_more'),
        ('accounts', '0004_notificationpreference'),
    ]

    operations = [
    ]
