# Generated by Django 5.2.17 on 2026-10-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registry_import_batch'),
        ('accounts', '0006_user_announcement_alerts'),
    ]

    operations = [
    ]
