import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { malaysiaDeadline, CompletionWindowHistory, MarksCompletionWindows } from './MarksCompletionWindows';
import { ClosureSummary } from './ClosureReview';
const row:any={id:1,taskId:2,deadline:'2026-10-01T04:00:00Z',status:'ACTIVE',reason:'Complete original draft',grantedBy:{id:3,name:'Office Staff'},createdAt:'2026-09-22T01:00:00Z',revokedAt:null,revocationReason:'',supersedesId:null,canRevoke:true};
const render=(window:any)=>renderToStaticMarkup(<CompletionWindowHistory windows={[window]} onRevoke={()=>{}}/>);
assert.match(render(row),/Revoke window/);
assert.match(render(row),/12:00 pm \(Malaysia, UTC\+08:00\)/);
assert.doesNotMatch(render({...row,status:'EXPIRED',canRevoke:false}),/Revoke window/);
assert.match(render({...row,status:'REVOKED',canRevoke:false,revokedAt:row.createdAt,revocationReason:'Wrong task'}),/Wrong task/);
assert.equal(malaysiaDeadline('2026-10-01T12:00'),'2026-10-01T04:00:00.000Z');
assert.throws(()=>malaysiaDeadline('2026-02-30T12:00'),/valid/);
assert.throws(()=>malaysiaDeadline('2026-10-01'),/valid/);
const office=renderToStaticMarkup(<MarksCompletionWindows tasks={[{taskId:2,studentName:'Old semester student',panelMember:'Dr Panel',status:'DRAFT',semester:'Closed semester',canGrantCompletionWindow:true},{taskId:3,studentName:'Submitted student',panelMember:'Dr Panel',status:'SUBMITTED',canGrantCompletionWindow:false}] as any} onChanged={async()=>{}}/>);
assert.match(office,/Old semester student/);
assert.match(office,/aria-label="Select Submitted student, Dr Panel" disabled=""/);
const counts={submitted:10,notStarted:2,draft:3,paused:1,activeWindows:2,unfinished:6};
const preview=renderToStaticMarkup(<ClosureSummary preview={{previewToken:'secret-preview-token',semesterId:1,periods:[{...counts,periodId:2,name:'Previous period'}],totals:counts,requiresAcknowledgement:true}}/>);
assert.match(preview,/Previous period/);assert.match(preview,/Active windows/);assert.doesNotMatch(preview,/secret-preview-token|studentId|scores/);
console.log('Completion history, eligible historical tasks, Malaysia time and closure summary passed');
