# Generated by Django 5.2.15 on 2026-06-05 08:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=128)),
                ('proposed_topic', models.CharField(max_length=500)),
                ('research_area', models.CharField(blank=True, max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_profile', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_research_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='PanelRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_PANEL', 'Submitted to Panel'), ('REJECTED_BY_PANEL', 'Rejected by Panel'), ('ACCEPTED_BY_PANEL', 'Accepted by Panel'), ('PENDING_COORDINATOR', 'Pending Coordinator'), ('REJECTED_BY_COORDINATOR', 'Rejected by Coordinator'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=32)),
                ('justification', models.TextField(blank=True)),
                ('panel_rejection_reason', models.TextField(blank=True)),
                ('coordinator_rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('panel_decided_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_recommendations_to_review', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_panel_recommendations', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_recommendations', to='appointments.studentresearchprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_panel_appointments', to=settings.AUTH_USER_MODEL)),
                ('panel_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_appointments', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_panel_appointments', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='panel_appointment', to='appointments.panelrecommendation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_appointments', to='appointments.studentresearchprofile')),
            ],
            options={
                'ordering': ['-appointment_date', 'profile__student_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='panelrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED_TO_PANEL', 'ACCEPTED_BY_PANEL', 'PENDING_COORDINATOR', 'APPROVED'])), fields=('profile',), name='one_active_panel_recommendation_per_student'),
        ),
    ]
