# Generated by Django 5.2.15 on 2026-06-22 08:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentregistry'),
        ('appointments', '0003_remove_panel_recommendation_draft_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=500)),
                ('research_abstract', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED_TO_SUPERVISOR', 'Submitted to Supervisor'), ('REJECTED_BY_SUPERVISOR', 'Rejected by Supervisor'), ('PENDING_COORDINATOR', 'Pending Coordinator'), ('REJECTED_BY_COORDINATOR', 'Rejected by Coordinator'), ('APPROVED', 'Approved')], db_index=True, default='SUBMITTED_TO_SUPERVISOR', max_length=32)),
                ('supervisor_rejection_reason', models.TextField(blank=True)),
                ('coordinator_rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supervisor_decided_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_applications_to_review', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_applications', to='accounts.student')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('previous_status', models.CharField(blank=True, max_length=64)),
                ('new_status', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('panel_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='appointments.panelrecommendation')),
                ('supervisor_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='appointments.supervisorapplication')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appointments.supervisorapplication')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.supervisorapplication')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_supervisor_appointments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_appointments', to='accounts.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_supervisor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_date', 'student__matric_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='supervisorapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED_TO_SUPERVISOR', 'PENDING_COORDINATOR', 'APPROVED'])), fields=('student',), name='one_active_supervisor_application_per_student'),
        ),
        migrations.AddConstraint(
            model_name='appointmentworkflowevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('panel_recommendation__isnull', False), ('supervisor_application__isnull', True)), models.Q(('panel_recommendation__isnull', True), ('supervisor_application__isnull', False)), _connector='OR'), name='workflow_event_has_exactly_one_record'),
        ),
    ]
