# Generated by Django 5.2.15 on 2026-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_supervisordocumentrequirement_supervisorapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelrecommendation',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='panelrecommendation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecommendation',
            name='status',
            field=models.CharField(choices=[('SUBMITTED_TO_PANEL', 'Submitted to Panel'), ('REJECTED_BY_PANEL', 'Rejected by Panel'), ('ACCEPTED_BY_PANEL', 'Accepted by Panel'), ('PENDING_COORDINATOR', 'Pending Coordinator'), ('REJECTED_BY_COORDINATOR', 'Rejected by Coordinator'), ('CANCELLED_BY_SUPERVISOR', 'Cancelled by Supervisor'), ('APPROVED', 'Approved')], db_index=True, default='SUBMITTED_TO_PANEL', max_length=32),
        ),
    ]
