# Generated by Django 5.2.15 on 2026-06-23 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_panelrecommendation_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='panelrecommendation',
            name='one_active_panel_recommendation_per_student',
        ),
        migrations.AddField(
            model_name='supervisorapplication',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supervisorapplication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelrecommendation',
            name='status',
            field=models.CharField(choices=[('SUBMITTED_TO_PANEL', 'Submitted to Panel'), ('REJECTED_BY_PANEL', 'Rejected by Panel'), ('PENDING_COORDINATOR', 'Pending Coordinator'), ('REJECTED_BY_COORDINATOR', 'Rejected by Coordinator'), ('CANCELLED_BY_SUPERVISOR', 'Cancelled by Supervisor'), ('APPROVED', 'Approved')], db_index=True, default='SUBMITTED_TO_PANEL', max_length=32),
        ),
        migrations.AlterField(
            model_name='supervisorapplication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED_TO_SUPERVISOR', 'Submitted to Supervisor'), ('REJECTED_BY_SUPERVISOR', 'Rejected by Supervisor'), ('PENDING_COORDINATOR', 'Pending Coordinator'), ('REJECTED_BY_COORDINATOR', 'Rejected by Coordinator'), ('CANCELLED_BY_STUDENT', 'Cancelled by Student'), ('APPROVED', 'Approved')], db_index=True, default='SUBMITTED_TO_SUPERVISOR', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='panelrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED_TO_PANEL', 'PENDING_COORDINATOR', 'APPROVED'])), fields=('profile',), name='one_active_panel_recommendation_per_student'),
        ),
    ]
