# Generated by Django 5.2.15 on 2026-07-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('appointments', '0006_remove_panelrecommendation_one_active_panel_recommendation_per_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelrecommendation',
            name='academic_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_recommendations', to='academics.academicsemester'),
        ),
        migrations.AddField(
            model_name='supervisorapplication',
            name='academic_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_applications', to='academics.academicsemester'),
        ),
    ]
