# Generated by Django 5.2.15 on 2026-07-31 15:10

import appointments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_panelrecommendation_academic_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorapplicationdocument',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supervisorapplicationdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=appointments.models.supervisor_document_upload_path),
        ),
        migrations.AddField(
            model_name='supervisorapplicationdocument',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='appointments.supervisordocumentrequirement'),
        ),
        migrations.AddField(
            model_name='supervisorapplicationdocument',
            name='requirement_code',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supervisorapplicationdocument',
            name='requirement_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SupervisorDocumentRequirementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_document_requirement_audits', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='appointments.supervisordocumentrequirement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supervisorapplicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('requirement__isnull', False)), fields=('application', 'requirement'), name='one_supervisor_document_per_requirement'),
        ),
    ]
