# Generated by Django 5.2.15 on 2026-08-12 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0003_studentregistry"),
        ("appointments", "0009_supervisorapplication_research_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ACTIVATED", "Activated"),
                            ("ENDED", "Ended"),
                            ("REPLACED", "Replaced"),
                        ],
                        max_length=16,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=16)),
                ("new_status", models.CharField(max_length=16)),
                ("outcome", models.CharField(blank=True, max_length=16)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="panelrecommendation",
            name="one_active_panel_recommendation_per_student",
        ),
        migrations.RemoveConstraint(
            model_name="supervisorapplication",
            name="one_active_supervisor_application_per_student",
        ),
        migrations.AddField(
            model_name="panelappointment",
            name="end_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("REPLACED", "Replaced"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("OTHER", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="panelappointment",
            name="end_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="panelappointment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="panelappointment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ended_panel_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="panelappointment",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_appointment",
                to="appointments.panelappointment",
            ),
        ),
        migrations.AddField(
            model_name="panelrecommendation",
            name="replacement_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="panelrecommendation",
            name="replaces_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_recommendations",
                to="appointments.panelappointment",
            ),
        ),
        migrations.AddField(
            model_name="supervisorapplication",
            name="replacement_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supervisorapplication",
            name="replaces_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_applications",
                to="appointments.supervisorappointment",
            ),
        ),
        migrations.AddField(
            model_name="supervisorappointment",
            name="end_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("REPLACED", "Replaced"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("OTHER", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="supervisorappointment",
            name="end_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supervisorappointment",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supervisorappointment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ended_supervisor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supervisorappointment",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_appointment",
                to="appointments.supervisorappointment",
            ),
        ),
        migrations.AlterField(
            model_name="panelappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ENDED", "Ended"),
                    ("COMPLETED", "Completed"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="panelappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("profile",),
                name="one_active_panel_appointment_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="panelrecommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["SUBMITTED_TO_PANEL", "PENDING_COORDINATOR"])
                ),
                fields=("profile",),
                name="one_active_panel_recommendation_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="supervisorapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["SUBMITTED_TO_SUPERVISOR", "PENDING_COORDINATOR"])
                ),
                fields=("student",),
                name="one_active_supervisor_application_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="supervisorappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student",),
                name="one_active_supervisor_appointment_per_student",
            ),
        ),
        migrations.AddField(
            model_name="appointmentlifecycleevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment_lifecycle_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointmentlifecycleevent",
            name="panel_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifecycle_events",
                to="appointments.panelappointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentlifecycleevent",
            name="supervisor_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifecycle_events",
                to="appointments.supervisorappointment",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentlifecycleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("panel_appointment__isnull", True),
                        ("supervisor_appointment__isnull", False),
                    ),
                    models.Q(
                        ("panel_appointment__isnull", False),
                        ("supervisor_appointment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="lifecycle_event_has_exactly_one_appointment",
            ),
        ),
    ]
