# Generated by Django 5.2.15 on 2026-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_appointmentlifecycleevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panelrecommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED_TO_PANEL", "Submitted to Panel"),
                    ("REJECTED_BY_PANEL", "Rejected by Panel"),
                    ("PENDING_COORDINATOR", "Pending Coordinator"),
                    ("REJECTED_BY_COORDINATOR", "Rejected by Coordinator"),
                    ("CANCELLED_BY_SUPERVISOR", "Cancelled by Supervisor"),
                    ("CANCELLED_BY_OFFICE", "Cancelled by Office"),
                    ("APPROVED", "Approved"),
                ],
                db_index=True,
                default="SUBMITTED_TO_PANEL",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="supervisorapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED_TO_SUPERVISOR", "Submitted to Supervisor"),
                    ("REJECTED_BY_SUPERVISOR", "Rejected by Supervisor"),
                    ("PENDING_COORDINATOR", "Pending Coordinator"),
                    ("REJECTED_BY_COORDINATOR", "Rejected by Coordinator"),
                    ("CANCELLED_BY_STUDENT", "Cancelled by Student"),
                    ("CANCELLED_BY_OFFICE", "Cancelled by Office"),
                    ("APPROVED", "Approved"),
                ],
                db_index=True,
                default="SUBMITTED_TO_SUPERVISOR",
                max_length=32,
            ),
        ),
    ]
