# Generated by Django 5.2.15 on 2026-09-12 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_seed_capacity_baselines"),
        ("accounts", "0004_lecturer_lifecycle_changed_at_and_more"),
        ("appointments", "0011_alter_panelrecommendation_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoSupervisorAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "end_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("REPLACED", "Replaced"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("end_reason", models.TextField(blank=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-appointment_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="CoSupervisorNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED_TO_CO_SUPERVISOR", "Awaiting co-supervisor"),
                            ("PENDING_COORDINATOR", "Awaiting coordinator"),
                            ("APPROVED", "Approved"),
                            ("REJECTED_BY_CO_SUPERVISOR", "Rejected by co-supervisor"),
                            ("REJECTED_BY_COORDINATOR", "Rejected by coordinator"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED_TO_CO_SUPERVISOR",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("candidate_decided_at", models.DateTimeField(blank=True, null=True)),
                ("coordinator_decided_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="appointmentlifecycleevent",
            name="lifecycle_event_has_exactly_one_appointment",
        ),
        migrations.RemoveConstraint(
            model_name="appointmentworkflowevent",
            name="workflow_event_has_exactly_one_record",
        ),
        migrations.AddField(
            model_name="cosupervisorappointment",
            name="approved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_co_supervisor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cosupervisorappointment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ended_co_supervisor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cosupervisorappointment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="co_supervisor_appointments",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisorappointment",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_appointment",
                to="appointments.cosupervisorappointment",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisorappointment",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="co_supervisor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointmentlifecycleevent",
            name="co_supervisor_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifecycle_events",
                to="appointments.cosupervisorappointment",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentlifecycleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("co_supervisor_appointment__isnull", True),
                        ("panel_appointment__isnull", True),
                        ("supervisor_appointment__isnull", False),
                    ),
                    models.Q(
                        ("co_supervisor_appointment__isnull", True),
                        ("panel_appointment__isnull", False),
                        ("supervisor_appointment__isnull", True),
                    ),
                    models.Q(
                        ("co_supervisor_appointment__isnull", False),
                        ("panel_appointment__isnull", True),
                        ("supervisor_appointment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="lifecycle_event_has_exactly_one_appointment",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisornomination",
            name="academic_semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="co_supervisor_nominations",
                to="academics.academicsemester",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisornomination",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="co_supervisor_nominations_to_review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cosupervisornomination",
            name="nominator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_co_supervisor_nominations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cosupervisornomination",
            name="primary_appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="co_supervisor_nominations",
                to="appointments.supervisorappointment",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisornomination",
            name="replaces_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_nominations",
                to="appointments.cosupervisorappointment",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisornomination",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="co_supervisor_nominations",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="cosupervisorappointment",
            name="nomination",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment",
                to="appointments.cosupervisornomination",
            ),
        ),
        migrations.AddField(
            model_name="appointmentworkflowevent",
            name="co_supervisor_nomination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_events",
                to="appointments.cosupervisornomination",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentworkflowevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("co_supervisor_nomination__isnull", True),
                        ("panel_recommendation__isnull", False),
                        ("supervisor_application__isnull", True),
                    ),
                    models.Q(
                        ("co_supervisor_nomination__isnull", True),
                        ("panel_recommendation__isnull", True),
                        ("supervisor_application__isnull", False),
                    ),
                    models.Q(
                        ("co_supervisor_nomination__isnull", False),
                        ("panel_recommendation__isnull", True),
                        ("supervisor_application__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="workflow_event_has_exactly_one_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="cosupervisornomination",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["SUBMITTED_TO_CO_SUPERVISOR", "PENDING_COORDINATOR"],
                    )
                ),
                fields=("student", "candidate"),
                name="unique_pending_co_supervisor_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="cosupervisornomination",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["SUBMITTED_TO_CO_SUPERVISOR", "PENDING_COORDINATOR"],
                    )
                ),
                fields=("replaces_appointment",),
                name="unique_pending_co_supervisor_replacement",
            ),
        ),
        migrations.AddConstraint(
            model_name="cosupervisorappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("student", "supervisor"),
                name="unique_active_co_supervisor_candidate",
            ),
        ),
    ]
