# Generated by Django 5.2.17 on 2026-09-24 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_seed_capacity_baselines"),
        ("accounts", "0005_coordinatordelegation"),
        ("appointments", "0012_co_supervisor_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresearchprofile",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ResearchAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RESEARCH", "Research amendment"),
                            ("TRANSFER", "Programme transfer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SUPERVISOR", "Awaiting primary supervisor"),
                            ("PENDING_COORDINATOR", "Awaiting programme coordinator"),
                            (
                                "PENDING_SOURCE_COORDINATOR",
                                "Awaiting source coordinator",
                            ),
                            (
                                "PENDING_DESTINATION_COORDINATOR",
                                "Awaiting destination coordinator",
                            ),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("source_programme", models.CharField(max_length=255)),
                ("destination_programme", models.CharField(blank=True, max_length=255)),
                ("before_values", models.JSONField()),
                ("after_values", models.JSONField()),
                ("baseline_revision", models.PositiveIntegerField()),
                ("team_snapshot", models.JSONField(default=dict)),
                ("semester_snapshot", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                ("student_name", models.CharField(max_length=255)),
                ("matric_no", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.academicsemester",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_research_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments",
                        to="appointments.studentresearchprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_amendments",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ResearchAmendmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(max_length=64)),
                ("actor_name", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=32)),
                ("previous_status", models.CharField(blank=True, max_length=40)),
                ("new_status", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True)),
                ("retain_team", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="appointments.researchamendment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProfileRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=16)),
                ("before_values", models.JSONField(default=dict)),
                ("after_values", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="appointments.studentresearchprofile",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_revision",
                        to="appointments.researchamendment",
                    ),
                ),
            ],
            options={
                "ordering": ["profile_id", "revision"],
            },
        ),
        migrations.AddConstraint(
            model_name="researchamendment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING_SUPERVISOR",
                            "PENDING_COORDINATOR",
                            "PENDING_SOURCE_COORDINATOR",
                            "PENDING_DESTINATION_COORDINATOR",
                        ],
                    )
                ),
                fields=("student",),
                name="one_pending_research_amendment_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchprofilerevision",
            constraint=models.UniqueConstraint(
                fields=("profile", "revision"), name="unique_research_profile_revision"
            ),
        ),
    ]
