# Generated by Django 5.2.17 on 2026-09-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_seed_capacity_baselines"),
        ("appointments", "0014_research_revision_baselines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityReassessmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(max_length=64)),
                ("actor_name", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GRANTED", "GRANTED"),
                            ("REPLACED", "REPLACED"),
                            ("REVOKED", "REVOKED"),
                            ("CONSUMED", "CONSUMED"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("request_status", models.CharField(max_length=40)),
                ("policy", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authorization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorization_events",
                        to="appointments.capacityreassessmentevent",
                    ),
                ),
                (
                    "co_supervisor_nomination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_reassessments",
                        to="appointments.cosupervisornomination",
                    ),
                ),
                (
                    "panel_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_reassessments",
                        to="appointments.panelrecommendation",
                    ),
                ),
                (
                    "supervisor_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_reassessments",
                        to="appointments.supervisorapplication",
                    ),
                ),
                (
                    "target_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.academicsemester",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("co_supervisor_nomination__isnull", True),
                                ("panel_recommendation__isnull", True),
                                ("supervisor_application__isnull", False),
                            ),
                            models.Q(
                                ("co_supervisor_nomination__isnull", False),
                                ("panel_recommendation__isnull", True),
                                ("supervisor_application__isnull", True),
                            ),
                            models.Q(
                                ("co_supervisor_nomination__isnull", True),
                                ("panel_recommendation__isnull", False),
                                ("supervisor_application__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="capacity_reassessment_one_request",
                    )
                ],
            },
        ),
    ]
