# Generated by Django 5.2.15 on 2026-07-29 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('academic_session', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('SEMESTER_I', 'Semester I'), ('SEMESTER_II', 'Semester II'), ('SPECIAL', 'Special Semester')], max_length=16)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('lifecycle_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_academic_semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSemesterAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ACTIVATE', 'Activate'), ('HANDOVER_CLOSE', 'Handover close'), ('CLOSE', 'Close'), ('EXTEND', 'Extend'), ('ARCHIVE', 'Archive')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_semester_audits', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='academics.academicsemester')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicsemester',
            constraint=models.UniqueConstraint(fields=('academic_session', 'term'), name='unique_academic_session_term'),
        ),
        migrations.AddConstraint(
            model_name='academicsemester',
            constraint=models.UniqueConstraint(condition=models.Q(('lifecycle_status', 'ACTIVE')), fields=('lifecycle_status',), name='one_active_academic_semester'),
        ),
        migrations.AddConstraint(
            model_name='academicsemester',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='academic_semester_valid_date_range'),
        ),
    ]
