# Generated by Django 5.2.15 on 2026-08-19 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0004_lecturer_lifecycle_changed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LecturerAvailabilityWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("SUPERVISOR", "Supervisor"), ("PANEL", "Panel")],
                        max_length=16,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "academic_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lecturer_availability_windows",
                        to="academics.academicsemester",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_lecturer_availability_windows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_lecturer_availability_windows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availability_windows",
                        to="accounts.lecturer",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_on", "ends_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="SemesterCapacityPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("COPIED_FORWARD", "Copied forward"),
                            ("MIGRATED_BASELINE", "Migrated baseline"),
                        ],
                        max_length=24,
                    ),
                ),
                ("publication_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_plans",
                        to="academics.academicsemester",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_capacity_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_capacity_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor_plans",
                        to="academics.semestercapacityplan",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_semester", "-version"],
            },
        ),
        migrations.CreateModel(
            name="LecturerCapacityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supervisor_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("panel_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_entries",
                        to="accounts.lecturer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_capacity_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="academics.semestercapacityplan",
                    ),
                ),
            ],
            options={
                "ordering": ["lecturer__staff_no"],
            },
        ),
        migrations.CreateModel(
            name="LecturerCapacityAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PLAN_CREATE", "Plan create"),
                            ("PLAN_COPY", "Plan copy"),
                            ("ENTRY_UPDATE", "Entry update"),
                            ("PUBLISH", "Publish"),
                            ("SUPERSEDE", "Supersede"),
                            ("AVAILABILITY_CREATE", "Availability create"),
                            ("AVAILABILITY_CANCEL", "Availability cancel"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("before_values", models.JSONField(default=dict)),
                ("after_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_audits",
                        to="academics.academicsemester",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lecturer_capacity_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "availability_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="academics.lectureravailabilitywindow",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_audits",
                        to="accounts.lecturer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="academics.semestercapacityplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="lectureravailabilitywindow",
            index=models.Index(
                fields=["lecturer", "role", "starts_on", "ends_on"],
                name="cap_window_lect_role_dates_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lectureravailabilitywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["SUPERVISOR", "PANEL"])),
                name="capacity_window_valid_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="lectureravailabilitywindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="cap_window_valid_date_range",
            ),
        ),
        migrations.AddIndex(
            model_name="semestercapacityplan",
            index=models.Index(
                fields=["academic_semester", "lifecycle_status"],
                name="cap_plan_sem_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="semestercapacityplan",
            constraint=models.UniqueConstraint(
                fields=("academic_semester", "version"),
                name="unique_capacity_plan_semester_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="semestercapacityplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lifecycle_status", "PUBLISHED")),
                fields=("academic_semester",),
                name="one_published_capacity_plan_per_semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="lecturercapacityentry",
            constraint=models.UniqueConstraint(
                fields=("plan", "lecturer"), name="unique_capacity_entry_plan_lecturer"
            ),
        ),
    ]
