import assert from 'node:assert/strict';
import * as api from './marksCompletionApi';
import { closeEvaluationPeriod } from './marksApi';
import { activateAcademicSemester, closeAcademicSemester } from './academicSemestersApi';
const calls: any[]=[];
globalThis.fetch = (async (url,init) => { calls.push({url:String(url),body:init?.body?JSON.parse(String(init.body)):null}); return new Response(JSON.stringify([])); }) as typeof fetch;
const approval={previewToken:'reviewed-token',acknowledgeUnfinished:true};
await api.grantCompletionWindows({taskIds:[2,3],deadline:'2026-10-01T12:00:00+08:00',reason:'Finish drafts'});
await api.getCompletionWindows(2);
await api.revokeCompletionWindow(8,'No longer needed');
await api.getClosurePreview('semester',4);
await api.getClosurePreview('handover',5);
await api.getClosurePreview('period',6);
await closeEvaluationPeriod(6,'Close',approval);
await closeAcademicSemester(4,'Close',approval);
await activateAcademicSemester(5,'Handover',approval);
assert.deepEqual(calls.map(c=>c.url),['/api/marks/completion-windows/','/api/marks/tasks/2/completion-windows/','/api/marks/completion-windows/8/revoke/','/api/academics/semesters/4/closure-preview/','/api/academics/semesters/5/handover-preview/','/api/marks/periods/6/closure-preview/','/api/marks/periods/6/close/','/api/academics/semesters/4/close/','/api/academics/semesters/5/activate/']);
for(const call of calls.slice(6)) assert.deepEqual(call.body,{reason:call===calls[8]?'Handover':'Close',...approval});
console.log('Completion and closure API contracts passed');
