# Generated by Django 5.2.15 on 2026-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineauditlog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('REPLACE', 'Replace'), ('ADD_ENTRY', 'Add Entry'), ('EDIT_ENTRY', 'Edit Entry'), ('DELETE_ENTRY', 'Delete Entry')], max_length=32),
        ),
    ]
