# Generated by Django 5.2.15 on 2026-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_timelineauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestertimelineentry',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
