# Generated by Django 5.2.15 on 2026-07-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('dashboard', '0003_semestertimelineentry_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semestertimeline',
            name='one_active_semester_timeline',
        ),
        migrations.AddField(
            model_name='semestertimeline',
            name='academic_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timelines', to='academics.academicsemester'),
        ),
        migrations.AddConstraint(
            model_name='semestertimeline',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_semester__isnull', False), ('is_active', True)), fields=('academic_semester',), name='one_current_timeline_per_semester'),
        ),
    ]
