export const PROGRAMME_OPTIONS = [
  'MASTER OF DATA SCIENCE (COURSEWORK)',
  'MASTER OF CYBER SECURITY (COURSEWORK)',
  'MASTER OF ARTIFICIAL INTELLIGENCE (COURSEWORK)',
] as const;

export type ProgrammeOption = typeof PROGRAMME_OPTIONS[number];

