# Generated by Django 5.2.15 on 2026-06-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('target', models.CharField(choices=[('All', 'Everyone'), ('All Students', 'All Students'), ('Lecturers', 'Lecturers'), ('Staff', 'Staff'), ('Coordinators', 'Coordinators')], default='All', max_length=32)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Info', 'Info'), ('General', 'General')], default='Info', max_length=16)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired')], default='Active', max_length=16)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service', models.CharField(default='Postgraduate Office', max_length=128)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('normal', 'Normal')], default='normal', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('is_announcement', models.BooleanField(default=True)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('module_label', models.CharField(blank=True, default='Announcement', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='announcements.announcement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='announcemen_recipie_5e73d9_idx')],
            },
        ),
    ]
