# Generated by Django 5.2.15 on 2026-06-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_date',
        ),
    ]
