# Generated by Django 5.2.15 on 2026-06-22 08:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_supervisordocumentrequirement_supervisorapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=128)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_evaluation_tasks', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_tasks', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='marks.evaluationperiod')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_tasks', to='appointments.studentresearchprofile')),
            ],
            options={
                'ordering': ['profile__student_name'],
            },
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], db_index=True, default='NOT_STARTED', max_length=16)),
                ('total_mark', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entry', to='marks.evaluationtask')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarkCorrectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CORRECT', 'Correct submitted marks'), ('REOPEN', 'Reopen submitted marks')], max_length=16)),
                ('reason', models.TextField()),
                ('before_values', models.JSONField()),
                ('after_values', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_correction_audits', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_audits', to='marks.markentry')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_periods', to='marks.rubric'),
        ),
        migrations.CreateModel(
            name='RubricComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='marks.rubric')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=7)),
                ('feedback', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='marks.markentry')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='marks.rubriccomponent')),
            ],
            options={
                'ordering': ['component__display_order', 'component_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationtask',
            constraint=models.UniqueConstraint(fields=('profile', 'evaluator', 'period'), name='unique_evaluation_task_assignment'),
        ),
        migrations.AddConstraint(
            model_name='rubriccomponent',
            constraint=models.UniqueConstraint(fields=('rubric', 'code'), name='unique_component_code_per_rubric'),
        ),
        migrations.AddConstraint(
            model_name='rubriccomponent',
            constraint=models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='rubric_component_max_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='markscore',
            constraint=models.UniqueConstraint(fields=('entry', 'component'), name='unique_score_per_entry_component'),
        ),
        migrations.AddConstraint(
            model_name='markscore',
            constraint=models.CheckConstraint(condition=models.Q(('marks_awarded__gte', 0)), name='mark_score_non_negative'),
        ),
    ]
