# Generated by Codex on 2026-06-24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evaluationtask",
            name="unique_evaluation_task_assignment",
        ),
        migrations.AddField(
            model_name="evaluationtask",
            name="evaluator_role",
            field=models.CharField(
                choices=[
                    ("SUPERVISOR", "Supervisor"),
                    ("PANEL", "Panel"),
                    ("BACKUP", "Backup / Manual Override"),
                ],
                db_index=True,
                default="PANEL",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="EvaluationTaskOverrideAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_task_override_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_task_overrides_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_task_overrides_replaced",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="override_audits",
                        to="marks.evaluationtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="evaluationtask",
            constraint=models.UniqueConstraint(
                fields=("profile", "evaluator", "period", "evaluator_role"),
                name="unique_evaluation_task_assignment",
            ),
        ),
    ]
