# Generated by Django 5.2.15 on 2026-07-28 14:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def populate_marks_configuration(apps, schema_editor):
    Rubric = apps.get_model("marks", "Rubric")
    EvaluationPeriod = apps.get_model("marks", "EvaluationPeriod")
    now = django.utils.timezone.now()

    for rubric in Rubric.objects.all():
        components = rubric.components.filter(is_active=True).order_by(
            "display_order",
            "id",
        )
        total = components.aggregate(total=models.Sum("max_marks"))["total"]
        rubric.family_code = rubric.code
        rubric.version = 1
        rubric.target_mark = total if total and total > 0 else Decimal("100.00")
        rubric.save(
            update_fields=["family_code", "version", "target_mark"],
        )
        for display_order, component in enumerate(components, start=1):
            if component.display_order != display_order:
                component.display_order = display_order
                component.save(update_fields=["display_order"])

    for period in EvaluationPeriod.objects.all():
        if period.is_open:
            period.lifecycle_status = "PUBLISHED"
            period.published_at = period.updated_at or now
        elif period.tasks.exists() or (
            period.closes_at is not None and period.closes_at < now
        ):
            period.lifecycle_status = "CLOSED"
            period.closed_at = period.closes_at or period.updated_at or now
        else:
            period.lifecycle_status = "DRAFT"
        period.save(
            update_fields=[
                "lifecycle_status",
                "published_at",
                "closed_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_evaluationtask_evaluator_role_and_override_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksConfigurationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('RUBRIC', 'Rubric'), ('PERIOD', 'Evaluation period')], max_length=16)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('before_values', models.JSONField(default=dict)),
                ('after_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='lifecycle_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AddField(
            model_name='evaluationperiod',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='family_code',
            field=models.SlugField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rubric',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newer_versions', to='marks.rubric'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='target_mark',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='rubric',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            populate_marks_configuration,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('family_code', 'version'), name='unique_rubric_family_version'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.CheckConstraint(condition=models.Q(('target_mark__gt', 0)), name='rubric_target_mark_positive'),
        ),
        migrations.AddConstraint(
            model_name='rubriccomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('rubric', 'display_order'), name='unique_active_component_order_per_rubric'),
        ),
        migrations.AddField(
            model_name='marksconfigurationaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_configuration_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='marksconfigurationaudit',
            index=models.Index(fields=['entity_type', 'entity_id'], name='marks_config_entity_idx'),
        ),
    ]
