# Generated by Django 5.2.15 on 2026-07-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('marks', '0003_marksconfigurationaudit_evaluationperiod_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationperiod',
            name='academic_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_periods', to='academics.academicsemester'),
        ),
    ]
