# Generated by Django 5.2.15 on 2026-08-12 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0004_evaluationperiod_academic_semester"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationtask",
            name="lifecycle_status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("RETIRED", "Retired")],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="evaluationtask",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluationtask",
            name="retired_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retired_evaluation_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluationtask",
            name="retirement_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="EvaluationTaskHandoverAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("draft_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_task_handover_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacement_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_handover_audits",
                        to="marks.evaluationtask",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_audits",
                        to="marks.evaluationtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
