# Generated by Django 5.2.17 on 2026-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0009_markentry_submitted_due_at_taskcompletionwindow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="markentry",
            name="submitted_due_recorded",
            field=models.BooleanField(default=False),
        ),
    ]
