# Generated by Django 5.2.15 on 2026-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('letter_type', models.CharField(default='Academic Certification', max_length=128)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft')], default='Draft', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Letter body. Use placeholders such as {{STUDENT_NAME}}, {{STUDENT_ID}}, {{PROGRAMME_NAME}}, {{CURRENT_STATUS}}, {{SUPERVISOR_NAME}}, {{REFERENCE_NUMBER}}, {{CURRENT_DATE}}.')),
                ('reference_prefix', models.CharField(blank=True, default='UMF/PG', max_length=64)),
                ('modified_by', models.CharField(blank=True, default='Office Staff', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
