# Generated by Django 5.2.17 on 2026-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Letter body with {{PLACEHOLDER}} tags; the allowed tags are listed in letters/placeholders.py.'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Draft', max_length=16),
        ),
    ]
